/* ==========================================================================
   MyOSINT Bookmarklet V9 Kit — REFERENCE SOURCE, not itself a bookmarklet.

   Purpose: canonical, working implementations of every piece described in
   the "Bookmarklet V9 Standard". Copy the functions a new/edited bookmarklet
   needs into its IIFE, rename as needed, then minify + encodeURIComponent()
   into the final `javascript:` href. Nothing here is loaded at runtime by
   any shipped bookmarklet — every bookmarklet must stay a single
   self-contained string with zero external fetches for its own UI code.

   Validated against the most V9-compliant shipped bookmarklets as of
   2026-07-13: google-maps-photo-extractor (modal shell, row format, export
   row) and trello-user-bookmarklet (export buttons, clipboard fallback,
   date urgency flag). Badge / two-pane / stat-counter blocks below encode
   the written spec directly since no shipped bookmarklet yet implements
   them exactly as specified — treat those as the target, not a copy of
   an existing one.
   ========================================================================== */

const V9 = {
  colors: {
    modalBg: '#022447',
    paneBg: '#033556',
    accent: '#008BC4',
    cyan: '#00E6F0',
    label: '#CCC',
    value: '#FFF',
    rowBorder: '#1a5276',
    urgent: '#FF4444',
    inactiveBg: '#444',
    inactiveText: '#999',
    inactiveBorder: '#555'
  },
  attribution: 'Generated by a bookmarklet from https://tools.myosint.training'
};

/* --------------------------------------------------------------------------
   1. Modal shell + drag. Returns {modal, header, body, close(fn)}.
   Caller appends `modal` to document.body whenever ready (immediately for a
   loading state, or only once data resolves).
   -------------------------------------------------------------------------- */
function v9CreateModal(title, opts) {
  opts = opts || {};
  // Responsive by default: width scales with the viewport (via clamp),
  // bounded so it never gets uncomfortably narrow or absurdly wide. A fixed
  // px width plus a max-width:92vw cap only ever SHRINKS on narrow viewports
  // and never grows on wide ones — that reads as "static" to a user who
  // resizes their window expecting the modal to follow. Pass opts.width to
  // force an exact fixed width in the rare case a layout genuinely needs one
  // (e.g. a two-pane modal where both panes have hard-pixel minimums); every
  // other bookmarklet should use the clamp default.
  const width = opts.width ||
    'clamp(' + (opts.minWidth || '420px') + ', ' + (opts.vw || '70vw') + ', ' + (opts.maxWidth || '900px') + ')';
  const modal = document.createElement('div');
  modal.style.cssText =
    'position:fixed;top:60px;left:50%;transform:translateX(-50%);' +
    'z-index:999999;background:' + V9.colors.modalBg + ';' +
    'border:2px solid ' + V9.colors.accent + ';border-radius:10px;' +
    'max-width:96vw;width:' + width + ';max-height:92vh;' +
    'font-family:Arial,sans-serif;box-shadow:0 8px 32px rgba(0,0,0,0.6);' +
    'display:flex;flex-direction:column;' +
    'user-select:text;-webkit-user-select:text;';

  // Version suffix (opts.version): a plain per-bookmarklet counter bumped by
  // hand whenever that bookmarklet is edited — NOT semver, NOT a shared/global
  // counter. It answers "has this specific bookmarklet changed since the user
  // last screenshotted it," nothing more, so it lives next to the title (the
  // thing it's actually versioning), styled as secondary info via the same
  // cyan already used for the hint/attribution line, not italics (no other
  // element in this design system uses italics).
  const versionHtml = opts.version
    ? ' <span style="color:' + V9.colors.cyan + ';font-weight:400;font-size:11px;">(v' + opts.version + ')</span>'
    : '';

  const header = document.createElement('div');
  header.style.cssText =
    'background:' + V9.colors.accent + ';padding:10px 16px;' +
    'border-radius:8px 8px 0 0;text-align:center;cursor:grab;' +
    'user-select:none;position:relative;flex-shrink:0;';
  // Two rows, not three: title(+version), then hint+attribution combined on
  // one logical line (it wraps to a visual second line on narrow modals,
  // which is fine — the point is not forcing a THIRD row's worth of margin).
  // The attribution text itself must stay byte-for-byte identical to
  // V9.attribution — tests/test_bookmarklets.py's UNIVERSAL_ATTRIBUTION
  // constant and ~30 expectation JSON files substring-match on it.
  header.innerHTML =
    '<div style="color:#FFF;font-weight:600;font-size:14px;">' + title + versionHtml + '</div>' +
    '<div style="color:' + V9.colors.cyan + ';font-size:9px;margin-top:2px;">✋🏼 Drag to move · ' + V9.attribution + '</div>';

  const closeBtn = document.createElement('span');
  closeBtn.innerHTML = '×';
  closeBtn.style.cssText =
    'position:absolute;top:6px;right:12px;color:#FFF;font-size:22px;' +
    'cursor:pointer;line-height:1;';
  closeBtn.onclick = function () { modal.remove(); };
  header.appendChild(closeBtn);
  modal.appendChild(header);

  const body = document.createElement('div');
  body.style.cssText = 'padding:16px 20px;overflow-y:auto;flex:1;';
  modal.appendChild(body);

  let dragging = false, dx = 0, dy = 0;
  header.addEventListener('mousedown', function (e) {
    if (e.target === closeBtn) return;
    dragging = true;
    const r = modal.getBoundingClientRect();
    dx = e.clientX - r.left; dy = e.clientY - r.top;
    modal.style.transform = 'none';
    modal.style.left = r.left + 'px';
    modal.style.top = r.top + 'px';
  });
  document.addEventListener('mousemove', function (e) {
    if (dragging) {
      modal.style.left = (e.clientX - dx) + 'px';
      modal.style.top = (e.clientY - dy) + 'px';
    }
  });
  document.addEventListener('mouseup', function () { dragging = false; });

  return { modal: modal, header: header, body: body, closeBtn: closeBtn };
}

/* --------------------------------------------------------------------------
   2. Row format — label: value, left-justified.
   -------------------------------------------------------------------------- */
function v9Row(label, valueHtml) {
  const row = document.createElement('div');
  row.style.cssText = 'color:' + V9.colors.label + ';padding:6px 0;font-size:13px;';
  row.innerHTML = v9Esc(label) + ': <span style="color:' + V9.colors.value +
    ';font-weight:bold;font-family:\'Courier New\',monospace;">' + valueHtml + '</span>';
  return row;
}

/* --------------------------------------------------------------------------
   2b. Identity block — MANDATORY field order at the top of every extraction
   modal, before any other data: Username, Display Name, Account ID,
   Account URL, Account URL (ID-based variant, if the platform has one) —
   then a visual separator before whatever else the bookmarklet extracts.
   fields: {username, displayName, accountId, accountUrl, accountUrlWithId}
   — omit any key the platform doesn't have; the row for it is skipped
   entirely (never reorder the ones that do exist).
   -------------------------------------------------------------------------- */
function v9IdentityBlock(fields) {
  const wrap = document.createElement('div');
  if (fields.username) wrap.appendChild(v9Row('Username', v9Esc(fields.username)));
  if (fields.displayName) wrap.appendChild(v9Row('Display Name', v9Esc(fields.displayName)));
  if (fields.accountId) wrap.appendChild(v9Row('Account ID', v9Esc(fields.accountId)));
  if (fields.accountUrl) {
    wrap.appendChild(v9Row('Account URL',
      '<a href="' + v9Esc(fields.accountUrl) + '" target="_blank" rel="noreferrer" ' +
      'style="color:' + V9.colors.cyan + ';text-decoration:none;word-break:break-all;">' +
      v9Esc(fields.accountUrl) + '</a>'));
  }
  if (fields.accountUrlWithId) {
    wrap.appendChild(v9Row('Account URL (ID)',
      '<a href="' + v9Esc(fields.accountUrlWithId) + '" target="_blank" rel="noreferrer" ' +
      'style="color:' + V9.colors.cyan + ';text-decoration:none;word-break:break-all;">' +
      v9Esc(fields.accountUrlWithId) + '</a>'));
  }
  wrap.appendChild(v9IdentitySeparator());
  return wrap;
}
function v9IdentitySeparator() {
  const sep = document.createElement('div');
  sep.style.cssText = 'border-top:2px solid ' + V9.colors.accent + ';margin:10px 0 6px;padding-top:8px;';
  const lbl = document.createElement('div');
  lbl.textContent = 'Additional Information';
  lbl.style.cssText =
    'color:' + V9.colors.cyan + ';font-size:10px;font-weight:700;' +
    'text-transform:uppercase;letter-spacing:0.5px;margin-bottom:4px;';
  sep.appendChild(lbl);
  return sep;
}

/* --------------------------------------------------------------------------
   3. Timestamps — MANDATORY dual format (UTC/ISO + local) on every date.
   Pass isMs=true if the source timestamp is already milliseconds.
   -------------------------------------------------------------------------- */
function v9FormatISO(ts, isMs) {
  return new Date(isMs ? ts : ts * 1000).toISOString();
}
function v9FormatLocal(ts, isMs) {
  return new Date(isMs ? ts : ts * 1000).toLocaleString('en-US', {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit', second: '2-digit', timeZoneName: 'short'
  });
}
function v9IsWithin7Days(ts, isMs) {
  const target = new Date(isMs ? ts : ts * 1000);
  const diffDays = Math.floor((target - new Date()) / 86400000);
  return diffDays >= -7 && diffDays <= 7;
}
function v9TimestampRow(label, ts, isMs) {
  const urgent = v9IsWithin7Days(ts, isMs);
  const row = document.createElement('div');
  row.style.cssText = 'padding:6px 0;font-size:13px;';
  row.innerHTML =
    '<span style="color:' + V9.colors.label + ';">' + v9Esc(label) + ':</span> ' +
    (urgent ? '<span style="color:' + V9.colors.urgent + ';">🚨</span> ' : '') +
    '<span style="color:' + V9.colors.value + ';font-weight:bold;font-family:\'Courier New\',monospace;">' +
    v9FormatISO(ts, isMs) + '</span>' +
    '<div style="color:' + V9.colors.label + ';font-size:11px;margin-top:2px;">' +
    v9FormatLocal(ts, isMs) + '</div>';
  return row;
}

/* --------------------------------------------------------------------------
   4. Status badges — ALWAYS render every badge, active or not.
   list: [{label, active, color}]  (color = the "active" background color)

   Placement: this is a FOOTER BAR, the last element appended to the modal
   (after the content area, which already contains the export row) — not
   mixed inline into the data rows/stats. Append the returned element
   directly to `modal` (the v9CreateModal() return value), not to `body`.
   Matches the precedent in trello-user-bookmarklet.
   -------------------------------------------------------------------------- */
function v9BadgesFooter(list) {
  const footer = document.createElement('div');
  footer.style.cssText =
    'padding:12px 20px;background:' + V9.colors.paneBg + ';' +
    'border-top:1px solid ' + V9.colors.accent + ';border-radius:0 0 8px 8px;flex-shrink:0;';
  const lbl = document.createElement('div');
  lbl.textContent = 'Status:';
  lbl.style.cssText = 'color:' + V9.colors.cyan + ';font-size:11px;font-weight:bold;margin-bottom:8px;';
  footer.appendChild(lbl);
  const row = document.createElement('div');
  row.style.cssText = 'display:flex;gap:8px;flex-wrap:wrap;align-items:center;';
  list.forEach(function (b) {
    const el = document.createElement('span');
    if (b.active) {
      el.style.cssText =
        'background:' + b.color + ';color:#000;border:1px solid ' + b.color +
        ';padding:4px 8px;border-radius:4px;font-size:11px;font-weight:bold;';
    } else {
      el.style.cssText =
        'background:' + V9.colors.inactiveBg + ';color:' + V9.colors.inactiveText +
        ';border:1px solid ' + V9.colors.inactiveBorder +
        ';padding:4px 8px;border-radius:4px;font-size:11px;font-weight:bold;';
    }
    el.textContent = b.label;
    row.appendChild(el);
  });
  footer.appendChild(row);
  return footer;
}

/* --------------------------------------------------------------------------
   5. Compact stat counters (followers/following/answers/etc.) — horizontal
   bar, bold value over uppercase label, divided by border-right (not gap).
   stats: [{value, label}]
   -------------------------------------------------------------------------- */
function v9StatCounters(stats) {
  const bar = document.createElement('div');
  // Always an outer border on the whole bar (in addition to the internal
  // border-right dividers) — without it the bar blends into the modal
  // background and looks unfinished.
  bar.style.cssText =
    'display:flex;background:' + V9.colors.paneBg + ';' +
    'border:1px solid ' + V9.colors.accent + ';border-radius:4px;' +
    'margin:12px 0;overflow:hidden;';
  stats.forEach(function (s, i) {
    const cell = document.createElement('div');
    cell.style.cssText =
      'flex:1;text-align:center;padding:8px 4px;' +
      (i < stats.length - 1 ? 'border-right:1px solid ' + V9.colors.rowBorder + ';' : '');
    cell.innerHTML =
      '<div style="color:' + V9.colors.value + ';font-weight:bold;font-family:\'Courier New\',monospace;font-size:16px;">' +
      v9Esc(String(s.value)) + '</div>' +
      '<div style="color:' + V9.colors.label + ';font-size:10px;text-transform:uppercase;margin-top:2px;">' +
      v9Esc(s.label) + '</div>';
    bar.appendChild(cell);
  });
  return bar;
}

/* --------------------------------------------------------------------------
   6. Two-pane layout (data left, avatar/image right).
   HARD RULE: any profile/avatar image ALWAYS goes in the right pane via this
   function — never inline in the left content, never centered at the top
   of the modal. If a bookmarklet has an image and no other right-pane
   content, still use this layout just to place the image on the right.
   -------------------------------------------------------------------------- */
function v9TwoPane(leftEl, imageUrl) {
  const wrap = document.createElement('div');
  wrap.style.cssText = 'display:flex;align-items:stretch;';
  const left = document.createElement('div');
  left.style.cssText = 'flex:1;padding:16px 20px;';
  left.appendChild(leftEl);
  wrap.appendChild(left);

  const right = document.createElement('div');
  right.style.cssText =
    'flex:0 0 320px;background:' + V9.colors.paneBg + ';border-left:1px solid ' +
    V9.colors.accent + ';padding:16px;display:flex;align-items:flex-start;justify-content:center;';
  if (imageUrl) {
    right.innerHTML =
      '<a href="' + v9Esc(v9SafeUrl(imageUrl)) + '" target="_blank" rel="noreferrer">' +
      '<img src="' + v9Esc(imageUrl) + '" style="width:300px;height:300px;object-fit:cover;' +
      'border:2px solid ' + V9.colors.accent + ';border-radius:6px;display:block;" /></a>';
  } else {
    right.innerHTML =
      '<div style="padding:60px 10px;color:' + V9.colors.label +
      ';border:2px dashed ' + V9.colors.accent + ';border-radius:8px;text-align:center;width:100%;">No image available</div>';
  }
  wrap.appendChild(right);
  return wrap;
}

/* --------------------------------------------------------------------------
   7. Export row — Text / JSON / Excel Row / Excel Headers + right-aligned
   "Extracted: <time>" stamp. Only use on modals that extract/display data;
   omit on input-launcher / page-modifier bookmarklets.
   -------------------------------------------------------------------------- */
function v9MkExportBtn(label) {
  const b = document.createElement('button');
  b.textContent = label;
  b.style.cssText =
    'background:' + V9.colors.cyan + ';color:' + V9.colors.modalBg + ';border:none;' +
    'padding:3px 10px;border-radius:4px;cursor:pointer;font-size:12px;' +
    'font-weight:700;margin-right:6px;white-space:nowrap;';
  b.onmouseover = function () { this.style.background = V9.colors.accent; this.style.color = '#FFF'; };
  b.onmouseout = function () { this.style.background = V9.colors.cyan; this.style.color = V9.colors.modalBg; };
  return b;
}
function v9CopyToClipboard(btn, text, label) {
  const restore = function () {
    btn.textContent = '✓';
    btn.style.background = V9.colors.accent; btn.style.color = '#FFF';
    setTimeout(function () {
      btn.textContent = label;
      btn.style.background = V9.colors.cyan; btn.style.color = V9.colors.modalBg;
    }, 1500);
  };
  navigator.clipboard.writeText(text).then(restore).catch(function () {
    const ta = document.createElement('textarea');
    ta.value = text; ta.style.cssText = 'position:fixed;opacity:0;';
    document.body.appendChild(ta); ta.select();
    document.execCommand('copy'); document.body.removeChild(ta);
    restore();
  });
}
/* fields: {text, json, excelRow, excelHeaders} — each optional; omit any
   button whose data doesn't apply to this bookmarklet. */
function v9ExportRow(fields) {
  const row = document.createElement('div');
  row.style.cssText =
    'display:flex;align-items:center;flex-wrap:wrap;gap:6px;' +
    'border-top:1px solid ' + V9.colors.rowBorder + ';margin-top:12px;padding-top:12px;';
  const lbl = document.createElement('span');
  lbl.textContent = 'Export:';
  lbl.style.cssText = 'color:' + V9.colors.label + ';font-size:13px;font-weight:600;margin-right:2px;white-space:nowrap;';
  row.appendChild(lbl);

  if (fields.text) {
    const b = v9MkExportBtn('Text');
    b.onclick = function () { v9CopyToClipboard(b, fields.text, 'Text'); };
    row.appendChild(b);
  }
  if (fields.json) {
    const b = v9MkExportBtn('JSON');
    b.onclick = function () { v9CopyToClipboard(b, fields.json, 'JSON'); };
    row.appendChild(b);
  }
  if (fields.excelRow) {
    const b = v9MkExportBtn('Excel Row');
    b.onclick = function () { v9CopyToClipboard(b, fields.excelRow, 'Excel Row'); };
    row.appendChild(b);
  }
  if (fields.excelHeaders) {
    const b = v9MkExportBtn('Excel Headers');
    b.onclick = function () { v9CopyToClipboard(b, fields.excelHeaders, 'Excel Headers'); };
    row.appendChild(b);
  }

  const ts = document.createElement('span');
  ts.textContent = 'Extracted: ' + new Date().toLocaleString('en-US', {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit', second: '2-digit', timeZoneName: 'short'
  });
  ts.style.cssText = 'color:' + V9.colors.label + ';font-size:11px;margin-left:auto;white-space:nowrap;';
  row.appendChild(ts);

  return row;
}

/* --------------------------------------------------------------------------
   8. Small utilities used throughout the above.
   -------------------------------------------------------------------------- */
function v9Esc(s) {
  return String(s).replace(/[&<>"']/g, function (c) {
    return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c];
  });
}
/* v9SafeUrl: MANDATORY guard for any page/API-derived value used as an href
   or window.open() target (bio link, website/wishlist field, social link,
   avatar URL from an og:image meta tag, etc.) — self-constructed URLs (e.g.
   `baseUrl + '/users/show/' + uid`, or a hardcoded per-provider template)
   don't need this. HTML-escaping alone does NOT stop a value from carrying
   a `javascript:` scheme, which executes same-origin JS with the target
   site's session if a user clicks it. This forces anything not already
   starting with http(s):// to get that prefix, turning a `javascript:...`
   payload into a harmless, non-executing string instead
   (`https://javascript:alert(1)`). Apply at the point of use for the href;
   leave the displayed link TEXT as the original raw value. Found missing on
   7 shipped bookmarklets in the 2026-07-15 audit — see
   [[project-v9-sweep-progress]]. */
function v9SafeUrl(u) {
  return /^https?:\/\//i.test(u) ? u : 'https://' + u;
}
/* v9Linkify: the MANDATORY baseline for every bio/description field — every
   bare URL gets hyperlinked in place, target=_blank. Some platforms (X/Twitter's
   t.co, etc.) shorten links in the raw bio text and provide the real expanded
   destination + a friendlier display string elsewhere on the page; when that
   data is available, resolve to it instead of linking to the shortener,
   appending the external-link marker (see v9Linkify's plain-URL style below).
   Anchor the resolver on the shortened URL itself (guaranteed to appear
   verbatim in the raw bio text) and scan a window on BOTH sides of it for the
   display/expanded fields — don't assume they appear in a fixed order relative
   to each other, that's not a documented contract and silently breaks the
   whole match if the platform ever orders them differently (see
   [[project-x-twitter-jsonld-pattern]] for a full worked example). If a bio
   mixes shortened links and bare URLs, resolve the shortened ones first, then
   only run v9Linkify's bare-URL pass on text segments not already inside an
   <a> tag you just built — otherwise it will also match and corrupt the
   href="..." attribute value of those just-inserted links. */
function v9Linkify(text) {
  return v9Esc(text).replace(/(https?:\/\/[^\s]+|www\.[^\s]+)/g, function (url) {
    const href = url.startsWith('http') ? url : 'https://' + url;
    return '<a href="' + v9Esc(href) + '" target="_blank" rel="noreferrer" style="color:' +
      V9.colors.cyan + ';text-decoration:none;word-break:break-all;">' + v9Esc(url) + '</a>';
  });
}

/* ==========================================================================
   USAGE PATTERN for a new bookmarklet:

   1. Write readable source that does its own fetch/DOM-scraping, then calls
      the v9* helpers above to build the modal instead of inlining fresh
      CSS strings. Copy the `const V9 = {...}` palette block too — the
      helpers read from it.
   2. Assemble: const {modal, body} = v9CreateModal('My Bookmarklet Title');
      const left = document.createElement('div');
      left.appendChild(v9IdentityBlock({
        username: data.username, displayName: data.displayName,
        accountId: data.id, accountUrl: data.profileUrl,
        accountUrlWithId: data.profileUrlById // omit key entirely if platform has none
      }));
      left.appendChild(v9TimestampRow('Created', data.created_unix));
      left.appendChild(v9ExportRow({text: textBlob, json: JSON.stringify(data,null,2)}));
      // If there's a profile image, always use v9TwoPane to put it on the right —
      // never inline it in `left` or center it at the top:
      body.appendChild(data.avatarUrl ? v9TwoPane(left, data.avatarUrl) : left);
      // Badges are a footer bar, appended to the modal itself (after body),
      // not inside the scrollable content:
      modal.appendChild(v9BadgesFooter([{label:'Verified', active:data.verified, color:'#00E6F0'}]));
      document.body.appendChild(modal);
   3. Wrap the whole thing in (function(){ ... })(), minify, encodeURIComponent(),
      prepend 'javascript:', and paste into the <a href="..."> in index.html.
   4. node --check the unencoded source before encoding.
   5. Add tests/expectations/{slug}.json per [[reference-testing]].
   ========================================================================== */
